### ISSUE TITLE
Error when pulling usage for subscription

### ISSUE THREAD

**Issue by jeryanders** [isaiahwilliams/partner-center-open-dotnet#11]
I have a very simple console app:

```
using System;
using System.Threading.Tasks;
using Microsoft.Store.PartnerCenter;
namespace PartnerCenterTest
{
    public class PartnerCenterCredentials : IPartnerCredentials
    {
        public PartnerCenterCredentials(
                string partnerCenterToken
            )
        {
            PartnerServiceToken = partnerCenterToken;
        }

        public DateTimeOffset ExpiresAt => DateTime.Now.AddDays(7);

        public string PartnerServiceToken { get; set; }
        public bool IsExpired() => false;
    }
    class Program
    {
        static async Task Main(string[] args)
        {
            var partnerService = PartnerService.Instance;
            partnerService.ApiRootUrl = new Uri("https://api.partnercenter.microsoft.com/");
            var credentials = new PartnerCenterCredentials("--refresh-token--");
            var operation =  PartnerService.Instance.CreatePartnerOperations(credentials);
            var dailyUsage = await operation.Customers["--customer-id--"].Subscriptions["--subscription-id--"].UsageRecords.Daily.GetAsync();

            foreach(var usage in dailyUsage.Items)
            {
                Console.WriteLine($"{usage.DateUsed} - {usage.ResourceId} - {usage.ResourceName}");
            }
        }
    }
}
```

I'm getting an error on this. 

```
~/source/racker/PartnerCenterTest/src
$ dotnet run

Unhandled Exception: Microsoft.Store.PartnerCenter.Exceptions.PartnerException: Exception of type 'Microsoft.Store.PartnerCenter.Exceptions.PartnerException' was thrown.
   at Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.HandleResponseAsync[TResource](HttpResponseMessage response, JsonConverter converter)
   at Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.GetAsync[TResource](Uri relativeUri, IDictionary`2 headers, IDictionary`2 parameters, JsonConverter converter, CancellationToken cancellationToken)
   at Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.GetAsync[TResource](Uri relativeUri, JsonConverter converter, CancellationToken cancellationToken)
   at Microsoft.Store.PartnerCenter.Usage.SubscriptionDailyUsageRecordCollectionOperations.GetAsync(CancellationToken cancellationToken)
   at PartnerCenterTest.Program.Main(String[] args) in /Users/xxx/src/Program.cs:line 28
   at PartnerCenterTest.Program.<Main>(String[] args)
```

Am I setting this up correctly?

**Comment by jeryanders** [comment]
Nevermind. I figured this out.
